### PR TITLE
fix: Typos corected in codebase

### PR DESCRIPTION
**Pull request by HeetVekariya**
# Issue:
- Correct the typo in the codebase

## Found typos:
- Filename: **Starlcon** (src/components/common/Starlcon.jsx)
- Spelling mistake: **Generes** (src/components/shows/ShowMainData.jsx, line: 22)

## Changes made:
- Changed Filename to **StarIcon** (src/components/common/StarIcon.jsx)
  - **Import paths changed:** 
   - **ShowCard** (src/components/shows/ShowCard.jsx, line: 5)
  - **ShowMainData** (src/components/shows/ShowMainData.jsx, line: 2)

- Correct spell to **Genres** (src/components/shows/ShowMainData.jsx, line: 22) 

<br>
<br>

# Total changes made: 5

### CODE REVIEW

**Comment by HeetVekariya** [comment]
@mohitahlawat2001 Please check what is the wrong with my PR.

**Comment by HeetVekariya** [comment]
Can you please tell me what is wrong in it.

**Comment by mohitahlawat2001** [comment]
it make repo spammy to small spelling change , it does not affect user that much!

if it become spammy it will mark excluded for hacktoberfest by hacktoberfest site

**Comment by HeetVekariya** [comment]
Okay No problem, your query is valid. 👍

**Pull request closed without merging**
